# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/noom',
                'doc_host': 'https://vinay-jose.github.io',
                'git_url': 'https://github.com/vinay-jose/noom',
                'lib_path': 'noom'},
  'syms': { 'noom.core': { 'noom.core.Noom': ('core.html#noom', 'noom/core.py'),
                           'noom.core.Noom.__add__': ('core.html#noom.__add__', 'noom/core.py'),
                           'noom.core.Noom.__eq__': ('core.html#noom.__eq__', 'noom/core.py'),
                           'noom.core.Noom.__floordiv__': ('core.html#noom.__floordiv__', 'noom/core.py'),
                           'noom.core.Noom.__init__': ('core.html#noom.__init__', 'noom/core.py'),
                           'noom.core.Noom.__le__': ('core.html#noom.__le__', 'noom/core.py'),
                           'noom.core.Noom.__lt__': ('core.html#noom.__lt__', 'noom/core.py'),
                           'noom.core.Noom.__mul__': ('core.html#noom.__mul__', 'noom/core.py'),
                           'noom.core.Noom.__repr__': ('core.html#noom.__repr__', 'noom/core.py'),
                           'noom.core.Noom.__sub__': ('core.html#noom.__sub__', 'noom/core.py'),
                           'noom.core.Noom.__truediv__': ('core.html#noom.__truediv__', 'noom/core.py')}}}
