# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/noom',
                'doc_host': 'https://vinay-jose.github.io',
                'git_url': 'https://github.com/vinay-jose/noom',
                'lib_path': 'noom'},
  'syms': {'noom.core': {'noom.core.foo': ('core.html#foo', 'noom/core.py')}}}
